# Generated by Django 4.2.2 on 2023-06-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='longitude',
            new_name='long',
        ),
    ]
