# Generated by Django 4.2.2 on 2023-06-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_rename_latitude_coordinates_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinates',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='coordinates',
            old_name='long',
            new_name='longitude',
        ),
    ]
