# Generated by Django 4.2.2 on 2023-06-07 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities', '0003_alter_city_table'),
        ('coordinates', '0003_rename_lat_coordinates_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='coordinates',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
