# Generated by Django 4.2.2 on 2023-06-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
