# Generated by Django 4.2.2 on 2023-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_rename_cities_city_alter_city_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
